### ISSUE TITLE
Redirection to /auth after successful installation

### ISSUE THREAD

**Issue by arialblack14** [ericdude4/shopifex#1]
Hello @ericdude4 !
Nice package!

I am getting the following issue.
After I install my app on a shop on shopify, I always get redirected to the `/auth` route and the `select-store.html` page.
```
[info] GET /
[debug] Processing with MyAppWeb.EventController.index/2
  Parameters: %{"hmac" => "a98f23c8608bf76d1bddc43846ba08ff13a40a4e3r53408165af2aed6143c4f1", "locale" => "en", "session" => "54798671d0a9f8c3a5945b638c0cafd6c5438124bcfe8748107257f24f5bfb04", "shop" => "someshop.myshopify.com", "timestamp" => "1590785707"}
  Pipelines: [:browser, :shopify_session]
[info] Sent 302 in 632µs
[info] GET /auth
[debug] Processing with MyAppWeb.AuthController.auth/2
  Parameters: %{}
  Pipelines: [:browser, :shopify_entrypoint]
[info] Sent 200 in 603µs
```
Here is my router:
```
scope "/auth", MyAppWeb do
    pipe_through [:browser, :shopify_entrypoint]
    get "/", AuthController, :auth
    get "/install", AuthController, :install
  end

  scope "/", MyAppWeb do
    pipe_through [:browser, :shopify_session]

    get "/", EventController, :index
  end
```

Am I doing something wrong?

**Comment by ericdude4** [comment]
Hi @arialblack14, thanks! I'm glad you think so :)

In your Shopify parnter dashboard, for your app, under "App setup", what is your "App URL" set to? At the moment, you have to have this value set to "https://example.com/auth".

It looks like Shopify is trying to "enter" your app through the "https://example.com/" route, which then redirects to the "/auth" route, stripping out the GET parameters. 

Try updating your App URL in your Shopify App settings and let me know if that works. Does this make sense?

**Comment by arialblack14** [comment]
Thanks @ericdude4 :)
That was it, thank you!
