### ISSUE TITLE
Phoenix.Router halted in :shopify_session/2

### ISSUE THREAD

**Issue by smantzavinos** [ericdude4/shopifex#11]
Hey @ericdude4 , thanks for creating this library! I have followed the setup steps but am running into an issue.

When I try to load the app from within the Shopify admin I am getting the message "Phoenix.Router halted in :shopify_session/2"

The more complete output is shown below.

```
[info] GET /
[debug] Processing with ShopifyreviewbannerWeb.PageController.index/2
  Parameters: %{"hmac" => "98cda3f10d7dd300561753844f97f506c5211c6a080a4de95ca2cfd1a5af2ed8", "locale" => "en", "new_design_language" => "true", "session" => "60dbe1f2c7a34680df9aded2782e9ffecc3cd93dca67cb72343d6744b3988ec4", "shop" => "spirosdevtest.myshopify.com", "timestamp" => "1615287916"}
  Pipelines: [:shopify_browser, :shopify_session]
[debug] QUERY OK source="shops" db=0.9ms queue=1.7ms idle=931.2ms
SELECT s0."id", s0."access_token", s0."scope", s0."url", s0."inserted_at", s0."updated_at" FROM "shops" AS s0 WHERE (s0."url" = $1) ["spirosdevtest.myshopify.com"]
[info] Initiating shop installation for spirosdevtest.myshopify.com
[info] Sent 302 in 45ms
[debug] Phoenix.Router halted in :shopify_session/2
```

I am pretty new to Elixir and Phoenix so my debugging skills are not very good. Do you have any suggestions for what I could be doing wrong?

**Comment by ericdude4** [comment]
Hi @smantzavinos, sorry about that. I have been making lots of changes lately and I don't think the instructions may be missing some points, so bare with me.

Looks like the HMAC validation is failing for some reason. Have you configured your `config :shopifex, api_key: "asdf"` value so that it matches your Shopify app's secret key?

**Comment by smantzavinos** [comment]
Yes, I have performed the following config steps: 

- generated the shop schema
- updated my `config :shopifex` with values for all fields listed in the docs, including `api_key` and `secret`.
- Updated by endpoint.ex. Both the session_options with `secure: true` and `extra: "SameSite=None"` as well as updating the `plug Plug.Parsers`.
- I have added `ShopifexWeb.Routes.pipelines()` to the top of my router.ex. This one I was a little confused by and not sure I did it correctly. I just added this line at the root level of the module definition. In order to get it to compile I had to also add `require ShopifexWeb.Routes`. Is this the correct way to do it?
- I then added the `ShopifexWeb.Routes.auth_routes(...)` call and the other routes in the docs. Specifically `"/"`, `"/webhook"`, and `"/admin-links"`
- I defined the `AuthController` module, but did not create any functions in it.
- I also created the WebhookController. I only added the "uninstalled" hook for now, but I don't think that should be related.

I had originally followed the steps in the Medium article, but noticed there were a few differences with the docs, in the router in particular. After reviewing the steps to write this, I think I did all of documented setup steps.

Let me know what else I may have done incorrectly or could be missing. Thank you for the help!

**Comment by smantzavinos** [comment]
So I have done a little more digging, but I am still stuck. I do not believe the HMAC validation is failing. It is never actually making it to HMAC validation. I have added logs in the different steps to confirm. I have also used wireshark to inspect the packets going back and forth.

I am getting the initial request and getting into the redirect_to_install function. It is sending back what appears to be a valid redirect. But that's it, it ends there. No more packets are sent or received. 

On the shopify side it just says that my app refused to connect. I will keep digging. Do you have any suggestions about what could be going wrong?

**Comment by smantzavinos** [comment]
This issue turned out to be completely on my end. There were two things I changed that fixed it. 

1) I added <storeurl>/auth/install to whitelisted URL. Before I only add <storeurl>/auth/callback.

2) I uninstalled the existing "install" of the app and then reinstalled it. I had previously installed a next/react version I was playing around with. I don't recall if I had uninstalled it before. 

I'm not sure which (or both) ultimately fixed the issue but I now have access to the embedded app.

**Comment by ericdude4** [comment]
Hi @smantzavinos, thanks for the updates! I meant to get to this but I've been quite busy. I'm glad to hear you got it working now.

Please review my recent addition to the README on this project: https://github.com/ericdude4/shopifex/blob/master/README.md#maintaining-session-between-page-loads

This is a new feature which you will likely have to implement in your application.
