### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by themgt** [ericdude4/shopifex#12]
[GitHub](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license):
> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project.

Thanks!

**Comment by themgt** [comment]
Ahh I just noticed
https://github.com/ericdude4/shopifex/blob/master/mix.exs#L18

Since that's set in package definition it seems clear enough it's Apache-2.0 licensed, a LICENSE file might still be nice.

**Comment by ericdude4** [comment]
Good catch. I will add a license
