### ISSUE TITLE
Authenticating SPA Hosted Separately and Testing Related API Endpoints

### ISSUE THREAD

**Issue by lukashambsch** [ericdude4/shopifex#15]
First of all, thanks for the great package!

I noticed the docs recommend passing the session token into the head of the template. Since my SPA is hosted separately, I can't do that. Instead, I'm planning to expose an API endpoint that will return the token for the currently authenticated user. As a first step, I'm trying to use the authorized pipeline to restrict my current controllers. My tests are now failing because they aren't authenticated, so that's working as expected. Now I'm trying to figure out how to authenticate a user in the tests. Have you done this with any of your apps?

My first thought was to just use the `Shopifex.Plug.ShopifySession.put_shop_in_session` function to simulate an authenticated user. Since that isn't exposed I tried temporarily copying over the body of the function and using it, but I'm getting a `{:error, :secret_not_found}` response. I that error is coming from Guardian, but I don't know the exact cause because I have a secret key set in my config for `Shopifex.Guardian`. I'm guessing there are some intricacies I'm missing with the authentication.

Do you have any suggestions?

Thanks again for the package!

**Comment by ericdude4** [comment]
Hey, glad that you are finding this package useful! It's changing pretty fast these days so maybe the docs are out of date. If you are building a SPA with this package, consider this approach:

[Integrate Shopify session tokens into the Axios instance of your SPA.](https://shopify.dev/tutorials/use-session-tokens-with-axios) 

Then consider the following `router.ex` snippet:

```elixir
ShopifexWeb.Routes.pipelines()

pipeline :api do
  # add `{:cors_plug, "~> 2.0"}` to your deps
  plug CORSPlug, origin: "*"
  plug :accepts, ["json"]
end

# Shopifex.Guardian supports Shopify session_tokens out of the box
pipeline :authorized do
  plug(
    Guardian.Plug.Pipeline,
    module: Shopifex.Guardian,
    error_handler: ShopifyAppWeb.AuthErrorHandler
  )

  plug Guardian.Plug.VerifyHeader
  plug Guardian.Plug.EnsureAuthenticated
  plug Guardian.Plug.LoadResource
end

# These routes will take care of installation/update
ShopifexWeb.Routes.auth_routes(ShopifyAppWeb)

# API routes for your SPA to hit with the axios instance
scope "/api", ShopifyAppWeb do
  pipe_through [:api, :authorized]
  
  # An endpoint which your SPA can call on load to get whatever initialization data your app needs.
  options "/initialize", AuthController, :initialize
  get "/initialize", AuthController, :initialize
end
```
And for that initialization endpoint, maybe your `AuthController` can look something like this:
```elixir
defmodule ShopifyAppWeb.AuthController do
  use ShopifyAppWeb, :controller
  use ShopifexWeb.AuthController
  
  def initialize(conn, _params) do
    shop = Guardian.Plug.current_resource(conn)
    
    render(conn, "initialize.json", %{shop: shop})
  end
end
```
Then from your SPA:
```javascript
// Import your Shopify session_token axios instance
import api from './api';

const urlParams = new URLSearchParams(window.location.search);
const shopOrigin = urlParams.get('shop');

window.app = createApp({
  apiKey: "MY_SHOPIFY_API_KEY",
  shopOrigin,
});

// Use your axios instance to call the /api/initialize endpoint
const sessionData = await api.get('/api/initialize');
// Now you will have access to the current shop
```

I am in the process of adapting Shopifex to have SPA support, so this might all get abstracted behind some Shopifex macros soon. Hope this helps!

**Comment by lukashambsch** [comment]
@ericdude4 Thanks a lot for the examples! I'll give that a try today!

**Comment by lukashambsch** [comment]
It seems like what you're suggesting will work on the Shopifex side, but I'm running into a strange issue getting the Shopify token. When I call `getSessionToken` I get the following console error:

`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('<URL>') does not match the recipient window's origin ('<URL>').`

I know it isn't related to Shopifex, but just thought you may have run into it. I think it's related to hosting the BE & FE on different domains. I'm wondering if that isn't allowed by Shopify.

https://community.shopify.com/c/Shopify-APIs-SDKs/Can-I-run-my-frontend-and-backend-on-different-hosts-Shopify/td-p/816448

**Comment by ericdude4** [comment]
@lukashambsch I have an app running on separate BE/FE domains without a problem. Maybe you need to add this FE domain name to your Shopify app's redirect URI list or something? This response is coming from a request that your FE is making to the Shopify back end -- your BE is not involved from what you are telling me.

**Comment by lukashambsch** [comment]
Good to know that you can run them on separate domains without an issue. I'm initially authenticating from the BE using shopifex. After that I'm redirecting from `/` to the FE. Then I'm trying to using `getSessionToken` from there. The call to `getSessionToken` is where I'm getting the `Failed to execute 'postMessage'...` error. This is all running on localhost, so I have added that to my redirect URI list.

**Comment by ericdude4** [comment]
> Good to know that you can run them on separate domains without an issue. I'm initially authenticating from the BE using shopifex. After that I'm redirecting from `/` to the FE. Then I'm trying to using `getSessionToken` from there. The call to `getSessionToken` is where I'm getting the `Failed to execute 'postMessage'...` error. This is all running on localhost, so I have added that to my redirect URI list.

@lukashambsch would you be able to put together a minimum project which recreates this issue that I could use to check for any issues?

**Comment by lukashambsch** [comment]
At this point, I'm pretty certain it isn't an issue with Shopifex. Based on [this](https://community.shopify.com/c/Shopify-APIs-SDKs/Shopify-app-fails-when-outside-iframe-Failed-to-execute/m-p/1056149/highlight/true#M62387), I don't think I can use app bridge because my app isn't an embedded app. That's probably something I should've known, but I'm still new to Shopify apps.

So I guess what I need to figure out is how to use Shopifex to authenticate and provide the token to the FE without using app bridge. The initial authentication seems to work, then it redirects to the root url `/`. At that point I'm not sure how to provide a token to the frontend so it can make api requests.

**Comment by lukashambsch** [comment]
It looks like I should be able to access the token Shopifex creates with `Guardian.Plug.current_token(conn)` and pass that to the FE when I redirect. Just running into CORS issues now, but I'll let you know if I run into issues on the Shopifex side of things.

Thanks for all the help with this!

**Comment by ericdude4** [comment]
@lukashambsch Shopifex makes a JWT token available to any route which passes through the :shopify_session pipeline. Take a look at the "Maintaining session between page loads for server-rendered applications" section of the readme. Maybe you can pass this token to your javascript app from the EEx template which initializes your front end.

Does this help? Use this token in an authorization header for any requests that you make to your back end

**Comment by lukashambsch** [comment]
> @lukashambsch Shopifex makes a JWT token available to any route which passes through the :shopify_session pipeline. Take a look at the "Maintaining session between page loads for server-rendered applications" section of the readme. Maybe you can pass this token to your javascript app from the EEx template which initializes your front end.
> 
> Does this help? Use this token in an authorization header for any requests that you make to your back end

That's great! I'm giving that a shot and it looks like I can access it. I'm going to have to wait to figure out the CORS issues tomorrow, but I'll close this for now since those aren't Shopifex related.

Thanks!

**Comment by ericdude4** [comment]
@lukashambsch for CORS, use https://github.com/mschae/cors_plug

**Comment by lukashambsch** [comment]
Everything seems to be working. I just needed to use `CORSPlug` from the endpoint instead of the pipeline.

I really appreciate all of the help!

**Comment by lukashambsch** [comment]
@ericdude4 I still need to figure out how to mock an authenticated user so I can authenticate them to test my api endpoints and also the redirect from my page controller. Is there a simple way to do that?

For the api endpoints, it looks like I should be able to pass the shop into `Shopifex.Plug.ShopifySesssion.put_shop_in_session`, but that doesn't seem to do it.

**Comment by ericdude4** [comment]
I would suggest creating a shop_fixture() in your tests. Then in your test setup, use `Shopifex.Guardian.encode_and_sign\4` ([docs](https://hexdocs.pm/guardian/Guardian.html#encode_and_sign/4)) to create a token for that shop. Also in this setup method, add the token to an authorization header in your conn `Plug.Conn.put_req_header(conn, "Authorization", "Bearer #{token}")`.

Then in your tests you will have access to a `conn` struct which has an authorization header for the shop. This `conn` will be authorized to access all the routes which are piped through `:shopify_api` pipeline.

Does this help?

**Comment by lukashambsch** [comment]
@ericdude4 That's actually what I tried initially, but I got an `{:error, :secret_not_found}` response. I just figured out that was because my secret key wasn't loaded in my test env.

Thanks!
