### ISSUE TITLE
Persisting Sessions for Server Rendered Templates

### ISSUE THREAD

**Issue by lukashambsch** [ericdude4/shopifex#21]
It's me again with another authentication question. I'm trying to authenticate my live views, but it looks like the recommended way to persist sessions is by sending a `"token"` query parameter to every route. With my non-shopify apps, I usually just use `Plug.Conn.put_session(conn, :current_user_id)` when the user logs in and `Plug.Conn.delete_session(conn, :current_user_id)` when the user logs out. Is there any reason we couldn't substitute `:current_user_id` for `:current_shop_id` and do the same here? If we did that, we wouldn't have to pass the token around and the session would be persisted.

**Comment by ericdude4** [comment]
@lukashambsch The problem which passing a `token` parameter around addresses is the unreliability of cookies in an iFrame. For example, I believe Shopify apps which use cookies to maintain session wont work at all on Safari, and cookies are only getting more restricted over time.

Another option is to [build your application as a SPA](https://github.com/ericdude4/shopifex#single-page-applications) and make requests to your Shopifex API using the Shopify AppBridge session token . Shopifex ships with a `: shopify_api` router pipeline which will verify requests made with this token.

**Comment by lukashambsch** [comment]
Only embedded applications run in an iFrame, right? Would it be possible to keep the current support while also supporting storing the `current_shop_id` in the session? It seems like that would provide easier support for standalone applications while also addressing your concerns for embedded applications.

**Comment by lukashambsch** [comment]
I was just thinking something like this https://github.com/ericdude4/shopifex/pull/23

**Comment by ericdude4** [comment]
@lukashambsch What sort of app are you building that can make use of Shopifex and isn't an embedded application? Seems like you might only need a small subset of the tools which Shopifex provides.

Are you directing your users outside of the Shopify admin panel to use your app in a separate window? I think Shopify would reject the submission of such an app, no?

**Comment by lukashambsch** [comment]
Yes, it directs them outside of Shopify to use the app in a separate tab. I'm rewriting an existing app, but the first version is already live on Shopify, so no they didn't reject the submission.

**Comment by ericdude4** [comment]
@lukashambsch Interesting. I have seen older apps which I guess are grandfathered in. New apps will be rejected if they direct the user outside of the Shopify admin AFAIK.

In the spirit of being forward-looking, I think Shopifex will focus on modern app guidelines and leave out legacy app support. It should be easy to throw in a few extra custom router plugs to add support for your specific needs. i.e. you could make a plug which simply takes the values from `conn.private.shop` and puts them in the phoenix session.

**Comment by lukashambsch** [comment]
How old are the apps you have seen that are grandfathered in? This app is relatively new. It was created in the past year or so.

**Comment by ericdude4** [comment]
Your app doesn't render within the Shopify iFrame at all? Or you just have an external link in your app which brings a user into a different tab?

**Comment by lukashambsch** [comment]
I don't think it renders within an iFrame at all. The new tab is opened immediately after clicking the link to the app in the Shopify admin.
