### ISSUE TITLE
Could the phoenix_html version requirement be relaxed to include 3.0?

### ISSUE THREAD

**Issue by mfilej** [ericdude4/shopifex#29]
I was wondering whether the version requirement for `phoenix_html` could be changed to support 3.0. Is there any known issue?

https://github.com/ericdude4/shopifex/blob/c9a1977c5d50ccd738c59a095b855ee36c93161a/mix.exs#L57

**Comment by ericdude4** [comment]
@mfilej Sure! I don't know of any issues with this. Are you willing to make this PR?

**Comment by mfilej** [comment]
@ericdude4 Sure thing, will give it a go and make a PR if everything works out ok.

**Comment by mfilej** [comment]
FYI https://github.com/geolessel/react-phoenix/pull/58

**Comment by mfilej** [comment]
It seems that this was fixed in #32.

**Comment by ericdude4** [comment]
@mfilej Yes, we removed the dependency from Shopifex in https://github.com/ericdude4/shopifex/commit/3275150cbe9765f0bb0270055e175413c520fc1c. Hope you're all doing well. Cheers!
