### ISSUE TITLE
Auto-run ngrok and auto-update redirect uri

### ISSUE THREAD

**Issue by imricardoramos** [ericdude4/shopifex#41]
Hello, thanks for writing this library!

It seems the shopify cli uses an unofficial graphql mutation called `appUpdate`:
- https://github.com/Shopify/shopify-cli/blob/4723c60e85525212de78dc58cfe9957fede925af/lib/shopify_cli/services/app/serve/serve_service.rb#L35-L41
- https://github.com/Shopify/shopify-cli/blob/4723c60e85525212de78dc58cfe9957fede925af/lib/shopify_cli/tasks/update_dashboard_urls.rb#L16-L20
- https://github.com/Shopify/shopify-cli/blob/4723c60e85525212de78dc58cfe9957fede925af/lib/graphql/update_dashboard_urls.graphql

Maybe this could be run along side [ex_ngrok](https://github.com/joshuafleck/ex_ngrok) on app startup?

**Comment by ericdude4** [comment]
@imricardoramos Thanks for the suggestion, this sounds great! would you be interested in opening up a PR with this?

**Comment by imricardoramos** [comment]
Hey @ericdude4, I did make a slight attempt at this. However, it started to take too much of my time to reverse engineer the api (maybe I'm not skilled enough), so I aborted and ended up writing a bash script which worked just fine for me.
Doesn't mean it's a bad idea though, so I'm just leaving it here in case anyone wants to tackle it :) (maybe I'll try again in the future)

**Comment by ericdude4** [comment]
@imricardoramos I tried this same thing last year (looking through their cli source) and decided that paying for an ngrok subscription was easier 😆 

I will close this for now. Thanks for bringing it up!
