### ISSUE TITLE
Flash messages as a session storage

### ISSUE THREAD

**Issue by claudio-dalicandro** [ericdude4/shopifex#5]
Is there any reason to use flash messages in order to persist the shop in session? I don't understand why this is done, since it complicates things, couldn't you just use a key whose name was eventually replaceable in configuration?

**Comment by ericdude4** [comment]
@claudio-dalicandro I think it's just the easiest thing I could think of at the time to maintain the current shop in the session given the redirect-heavy nature of this package and the Shopify platform. If you have any better solutions I am most definitely accepting contributions!
