### ISSUE TITLE
Ecto.QueryError for GET /initialize-installation

### ISSUE THREAD

**Issue by cruisemaniac** [ericdude4/shopifex#65]
Hello there, I'm toying with a shopify app using the shopifex package.

After following the instructions and setting up my shopify partner account, I'm trying to install the app on a demo store. When I add the store URL in the `/auth` page and hit install,

I get the following error:

```
deps/shopifex/lib/shopifex/shops.ex:24: field `url` in `where` does not exist in schema ReportsElixir.ShopifyShops.ShopifyShop in query:
from s0 in ReportsElixir.ShopifyShops.ShopifyShop,
  where: s0.url == ^"powersellteststore.myshopify.com",
  select: s0
```

What am I missing / doing wrong in my setup that this isn't working? The migrations are perfect and the `shopify_shops` table has the following schema as intended:

```
CREATE TABLE IF NOT EXISTS public.shopify_shops
(
    id bigint NOT NULL DEFAULT nextval('shopify_shops_id_seq'::regclass),
    url character varying(255) COLLATE pg_catalog."default",
    access_token character varying(255) COLLATE pg_catalog."default",
    scope character varying(255) COLLATE pg_catalog."default",
    inserted_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    CONSTRAINT shopify_shops_pkey PRIMARY KEY (id)
)

CREATE UNIQUE INDEX IF NOT EXISTS shopify_shops_url_index
    ON public.shopify_shops USING btree
    (url COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;
```

Would love any help here.

**Comment by ericdude4** [comment]
Hi @cruisemaniac I think the mix task that creates the schemas doesn't put the `field :url, :string` (and other properties) in the schema. It's a bug with the `mix shopifex.install` script. You will need to manually add the appropriate fields to the schema files that Shopifex generated for you.

**Comment by cruisemaniac** [comment]
@ericdude4 Yeah, I dug around and found out.. Is this project still active and open for PRs? I'd not mind pushing in those 3 lines that make things work.

**Comment by ericdude4** [comment]
@cruisemaniac absolutely! Please feel free to make the fix and open a PR :)
