### ISSUE TITLE
Values for shop and repo

### ISSUE THREAD

**Issue by srameshr** [ericdude4/shopifex#7]
New to Elixir and Phoenix here.  What would be the values for MyApp.Repo and MyApp.Shop? Example of what kind of data and structure goes here?
```
repo: MyApp.Repo,
shop_schema: MyApp.Shop,
```

**Comment by ericdude4** [comment]
@srameshr  The repo will be the same module which is included as a child in `lib/my_app/application.ex`. It's the module which your app uses to communicate with your database.

shop_schema just needs `url` `access_token` `scope` fields defined in the schema (all strings).

**Comment by srameshr** [comment]
Could you share an actual example?

**Comment by ericdude4** [comment]
Sure! Here is an example of a shop:

```elixir
defmodule MyApp.Shop do
  use Ecto.Schema
  import Ecto.Changeset

  schema "shops" do
    field :url, :string
    field :scope, :string
    field :access_token, :string

    timestamps()
  end

  @doc false
  def changeset(shop, attrs) do
    shop
    |> cast(attrs, [:url, :scope, :access_token])
    |> validate_required([:url, :scope, :access_token])
  end
end
```

Here is an example of a repo. This should be auto-generated for you if you created your app w/ `mix phx.new`

```elixir
defmodule MyApp.Repo do
  use Ecto.Repo,
    otp_app: :my_app,
    adapter: Ecto.Adapters.Postgres
end
```

**Comment by srameshr** [comment]
@ericdude4 Looks like this package uses phoenix 1.5.1 and the rest of my packages depend on phoenix 1.4.7

```
Failed to use "phoenix" (version 1.4.17) because
  appsignal_phoenix (version 2.0.2) requires ~> 1.4
  kaffy (version 0.9.0) requires ~> 1.4
  phoenix_live_reload (version 1.2.2) requires ~> 1.4
  sentry (version 7.2.4) requires ~> 1.3
  shopifex (versions 0.2.0 and 0.2.1) requires ~> 1.5.1
  mix.lock specifies 1.4.17

** (Mix) Hex dependency resolution failed, change the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}
```

I tried override: true but it does not work. Should I downgrade shopifex version?

**Comment by srameshr** [comment]
Tried to downgrade as well as run mix.unlock mix.update it fails with the same error.

**Comment by ericdude4** [comment]
You should update to phoenix 1.5 https://gist.github.com/chrismccord/e53e79ef8b34adf5d8122a47db44d22f

**Comment by srameshr** [comment]
Other dependencies and modules break if I sway away from 1.4.7

How can I downgrade shopifex to use Phoenix 1.4.7?

**Comment by ericdude4** [comment]
@srameshr Have you tried? If you are on phoenix `1.5.x`, dependencies which rely on `1.4.x` should still work. `1.5.x` is backward compatible with `1.4.x`. Downgrading your deps to keep your old version of phoenix working is not the right way to go. You could create a fork of this library though if you really want to.

**Comment by srameshr** [comment]
@ericdude4 I managed to write a port of what this library does in NodeJS and redirect shopify auth to a  subdomain hosting this package. 
https://github.com/srameshr/shopify-auth-node

**Comment by ericdude4** [comment]
@srameshr Awesome! I am honored. Can you add some docs to your README so I can understand better what you mean?

**Comment by srameshr** [comment]
Pleasure! I thought it's better to write it in Nodejs than spend time learning Phoenix & Elixir :D
https://github.com/srameshr/shopify-auth-node

**Comment by ericdude4** [comment]
Cool! So it basically handles the login and installation process similar to Shopifex but with Node

**Comment by srameshr** [comment]
Yes. I keep publishing apps on Shopify and I thought it might be useful as a package to the community.
